
loading train data:    : 0it [00:00, ?it/s]

loading train data:    : 1955it [00:02, 977.01it/s]
loading train data:    : 3361it [00:07, 467.81it/s]
loading test data:    : 856it [00:00, 1936.55it/s]
Training:    :   0%|          | 0/160 [00:00<?, ?it/s]
> d:\ethz\internship\adaptive-e-learning-for-educational-recommendation-system\deepknowledgetracing-dkt-pytorch\dkt\knowledgetracing\evaluation\eval.py(31)forward()
-> p = temp.gather(0, index)[0]
(Pdb) device(type='cuda', index=0)
(Pdb) device(type='cpu')
Training:    :   0%|          | 0/160 [00:34<?, ?it/s]
Traceback (most recent call last):
  File "D:\ETHz\Internship\adaptive-e-learning-for-educational-recommendation-system\DeepKnowledgeTracing-DKT-Pytorch\DKT\KnowledgeTracing\evaluation\run.py", line 41, in <module>
    model, optimizer, train_loss = eval.train(trainLoaders, model, optimizer_adgd, loss_func,device)
  File "..\evaluation\eval.py", line 89, in train
    model, optimizer, loss = train_epoch(model, trainLoaders[i], optimizer, lossFunc,device)
  File "..\evaluation\eval.py", line 46, in train_epoch
    loss = loss_func(pred, batch)
  File "C:\Users\tyu06\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "..\evaluation\eval.py", line 31, in forward
    p = temp.gather(0, index)[0]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_gather)